branch-defaults:
  default:
    environment: image-filter-str-code-lldev-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filter-str-code-lldev
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
